(ns game-of-life.config)

(def ^:dynamic *win-name* "Game of life")
(def ^:dynamic *cell-width* 10)
(def ^:dynamic *cell-height* 10)
(def ^:dynamic *cell-fill-width* 9)
(def ^:dynamic *cell-fill-height* 9)
(def ^:dynamic *cell-n-horiz* 5)
(def ^:dynamic *cell-n-vert* 5)
(def ^:dynamic *win-width* (* *cell-n-horiz* *cell-width*))
(def ^:dynamic *win-height* (* *cell-n-vert* *cell-height*))
